programs:
  sleep_all:
    cmd: "/bin/sleep 3600"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/sleep_all.stdout
    stderr: /tmp/sleep_all.stderr
    env:
      STARTED_BY: taskmaster

  print_env:
    cmd: "/usr/bin/env"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/print_env.stdout
    stderr: /tmp/print_env.stderr
    env:
      STARTED_BY: taskmaster